version: 2
jobs:
  build:
    machine:
      node:
        version: 9.3.0
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /usr/src
    steps:
      - checkout
      - setup_remote_docker: docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: | npm run build:ci
