version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.0-ce-git
    working_directory: /usr/src
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: | npm run build:ci
